version: "3"

services:
  tile_builder:
    image: yuiseki/vector-tile-builder
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    entrypoint: "tileserver-gl-light"
    volumes:
      - ./docs:/app/docs
      - ./tmp:/app/tmp
    ports:
      - "3000:3000"
  mbtileserver:
    image: consbio/mbtileserver:latest
    container_name: mbtileserver
    entrypoint: /mbtileserver --enable-reload-signal
    restart: always
    volumes:
      - ./tmp:/tilesets
    ports:
      - 8080:8000
