version: "3"

services:
  tile_server:
    image: yuiseki/vector-tile-builder
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    entrypoint: "/app/entrypoint.sh"
    volumes:
      - ./docs:/app/docs
      - ./tmp:/app/tmp
    ports:
      - "9090:9090"
  charites:
    image: yuiseki/vector-tile-builder
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    command: make charites_server
    volumes:
      - ./docs:/app/docs
    ports:
      - "8080:8080"
